"""
Shared config for the Estados de Cuenta module.
Mirrors SG_CREDIT_CARD_PROJECT/config.py — kept here so Eudaimonia has no
dependency on the SG project being present (works standalone on Railway).
"""
import os

PDF_PASSWORD      = os.environ.get("PDF_PASSWORD", "")
PDF_PASSWORD_BBVA = os.environ.get("PDF_PASSWORD_BBVA", "")

MESES = {
    "ene": "01", "feb": "02", "mar": "03", "abr": "04",
    "may": "05", "jun": "06", "jul": "07", "ago": "08",
    "sep": "09", "oct": "10", "nov": "11", "dic": "12",
    "jan": "01", "apr": "04", "aug": "08", "dec": "12",
}

CATEGORIAS: dict[str, tuple[str, str]] = {
    "BURGER":               ("ALIMENTACION", "Fast Food"),
    "KFC":                  ("ALIMENTACION", "Fast Food"),
    "LITTLE CAESAR":        ("ALIMENTACION", "Fast Food"),
    "SUBWAY":               ("ALIMENTACION", "Fast Food"),
    "RESTAURANT":           ("ALIMENTACION", "Restaurante"),
    "TACO":                 ("ALIMENTACION", "Restaurante"),
    "VIPS":                 ("ALIMENTACION", "Restaurante"),
    "RAPPI":                ("ALIMENTACION", "Delivery"),
    "CARLS JR":             ("ALIMENTACION", "Fast Food"),
    "DOMINO":               ("ALIMENTACION", "Fast Food"),
    "WINGSTOP":             ("ALIMENTACION", "Fast Food"),
    "MCDONALDS":            ("ALIMENTACION", "Fast Food"),
    "COM RAP":              ("ALIMENTACION", "Delivery"),
    "BPK FASTFOOD":         ("ALIMENTACION", "Delivery"),
    "BUGALO":               ("ALIMENTACION", "Restaurante"),
    "KIMODO":               ("ALIMENTACION", "Restaurante"),
    "MERPAGO REST":         ("ALIMENTACION", "Restaurante"),
    "LOSWEROS":             ("ALIMENTACION", "Restaurante"),
    "PANADERIA":            ("CAFE/PAN", "Pan"),
    "PASTELES MARISA":      ("ALIMENTACION", "Restaurante"),
    "PAST MARISA":          ("ALIMENTACION", "Restaurante"),
    "CHILAQUILA":           ("ALIMENTACION", "Restaurante"),
    "SANTAROSALIA":         ("ALIMENTACION", "Restaurante"),
    "CAGUAMAS":             ("ALIMENTACION", "Restaurante"),
    "TOR PLANCHADAS":       ("ALIMENTACION", "Fast Food"),
    "REST QIN":             ("ALIMENTACION", "Fast Food"),
    "ELGUERO":              ("ALIMENTACION", "Restaurante"),
    "3039 PSAN LUIS":       ("ALIMENTACION", "Restaurante"),
    "MERPAGO ARELLANO":     ("ALIMENTACION", "Restaurante"),
    "MERPAGO AGREGADOR":    ("ALIMENTACION", "Restaurante"),
    "MERPAGO ASADAS":       ("ALIMENTACION", "Restaurante"),
    "MERPAGO LOSVOLCANES":  ("ALIMENTACION", "Restaurante"),
    "MERPAGO LOSVOLCAM":    ("ALIMENTACION", "Restaurante"),
    "MERPAGO LOSCUATES":    ("ALIMENTACION", "Restaurante"),
    "MERPAGO ELREY":        ("ALIMENTACION", "Restaurante"),
    "MERPAGO ELBIGOTES":    ("ALIMENTACION", "Restaurante"),
    "MERPAGO TAQUERIA":     ("ALIMENTACION", "Restaurante"),
    "MERPAGO CORTIJO":      ("ALIMENTACION", "Restaurante"),
    "MERPAGO DANI":         ("ALIMENTACION", "Restaurante"),
    "MERPAGO FAMILIALOSWER":("ALIMENTACION", "Restaurante"),
    "MERPAGO TIENDACHARLY": ("ALIMENTACION", "Restaurante"),
    "MERPAGO NOVEDADESLIA": ("ALIMENTACION", "Restaurante"),
    "MERPAGO VAMPIROS":     ("ALIMENTACION", "Restaurante"),
    "MERPAGO AMANDEL":      ("ALIMENTACION", "Restaurante"),
    "MERPAGO KOLOMITOS":    ("ALIMENTACION", "Restaurante"),
    "MERPAGO BBFLORES":     ("ALIMENTACION", "Restaurante"),
    "MERPAGO LABAOZERIAGDL":("ALIMENTACION", "Restaurante"),
    "MERPAGO PACHANGUITOS": ("ALIMENTACION", "Restaurante"),
    "MERPAGO CREPASTERRAN": ("ALIMENTACION", "Restaurante"),
    "MERPAGO CHOCLOYMAIZ":  ("ALIMENTACION", "Restaurante"),
    "MERPAGO QUEENLATINCLU":("DIGITAL", "Suscripciones entretenimiento"),
    "MERCADO PAGO":         ("ALIMENTACION", "Restaurante"),
    "MERCADOPAGO LOSVOLCA": ("ALIMENTACION", "Restaurante"),
    "POINTMP DONFREDY":     ("ALIMENTACION", "Restaurante"),
    "POINTMP ASADAS":       ("ALIMENTACION", "Restaurante"),
    "POINTMP ALIMENTOS":    ("ALIMENTACION", "Restaurante"),
    "POINTMP ARELLANO":     ("ALIMENTACION", "Restaurante"),
    "POINTMP CREPASTERRAN": ("ALIMENTACION", "Restaurante"),
    "POINTMP FAMILIALOSWER":("ALIMENTACION", "Restaurante"),
    "POINTMP TIENDACHARLY": ("ALIMENTACION", "Restaurante"),
    "POINTMP SERENAMORENA": ("ALIMENTACION", "Restaurante"),
    "POINTMP JUAN":         ("ALIMENTACION", "Restaurante"),
    "POINTMP TAQUERIA":     ("ALIMENTACION", "Restaurante"),
    "POINTMP MEMELOPOLIS":  ("ALIMENTACION", "Restaurante"),
    "POINTMP QUEENLATINCLU":("DIGITAL", "Suscripciones entretenimiento"),
    "POINTMP PUNTOCASINO":  ("SALSA", "Social"),
    "NETPAY TAQUERIA":      ("ALIMENTACION", "Restaurante"),
    "NETPAY LOS TARASCOS":  ("ALIMENTACION", "Restaurante"),
    "NETPAY EL REY":        ("ALIMENTACION", "Restaurante"),
    "PAYCLIP REST":         ("ALIMENTACION", "Restaurante"),
    "PAYCLIP GIRO":         ("ALIMENTACION", "Restaurante"),
    "CLIP MX REST":         ("ALIMENTACION", "Restaurante"),
    "BZPAYMX EL CANTON":    ("ALIMENTACION", "Restaurante"),
    "ABTS MARCELLA":        ("ALIMENTACION", "Restaurante"),
    "ABTS CMT":             ("ALIMENTACION", "Restaurante"),
    "ABTS 12480":           ("ALIMENTACION", "Restaurante"),
    "1305 MIDTOWN":         ("ALIMENTACION", "Restaurante"),
    "REST ":                ("ALIMENTACION", "Restaurante"),
    "PIZZERIA":             ("ALIMENTACION", "Restaurante"),
    "PIZZA":                ("ALIMENTACION", "Restaurante"),
    "TAQUERIA":             ("ALIMENTACION", "Restaurante"),
    "HAMBURGUESAS":         ("ALIMENTACION", "Restaurante"),
    "CARNITAS":             ("ALIMENTACION", "Restaurante"),
    "KARNITAS":             ("ALIMENTACION", "Restaurante"),
    "BIRRIA":               ("ALIMENTACION", "Restaurante"),
    "TRATTORIA":            ("ALIMENTACION", "Restaurante"),
    "RAMEN":                ("ALIMENTACION", "Restaurante"),
    "CHURROS":              ("ALIMENTACION", "Restaurante"),
    "TORTAS":               ("ALIMENTACION", "Restaurante"),
    "PESCADERIA":           ("ALIMENTACION", "Restaurante"),
    "CREPERIA":             ("ALIMENTACION", "Restaurante"),
    "PASTELERIA":           ("CAFE/PAN", "Pan"),
    "GORDITAS":             ("ALIMENTACION", "Fast Food"),
    "CARNES ":              ("ALIMENTACION", "Restaurante"),
    "CARNES ASADAS":        ("ALIMENTACION", "Restaurante"),
    "LA PARROQUIA":         ("ALIMENTACION", "Restaurante"),
    "DAIRY QUEEN":          ("ALIMENTACION", "Fast Food"),
    "MOSHI MOSHI":          ("ALIMENTACION", "Restaurante"),
    "YOGOCUP":              ("ALIMENTACION", "Restaurante"),
    "ESPIRAL LAVITOLA":     ("ALIMENTACION", "Restaurante"),
    "SAINT MICHEL":         ("CAFE/PAN", "Café"),
    "MAISON KAYSER":        ("CAFE/PAN", "Café"),
    "PLAZA PANAMERICANA":   ("ALIMENTACION", "Restaurante"),
    "HATO":                 ("ALIMENTACION", "Restaurante"),
    "LA TIZNADA":           ("ALIMENTACION", "Restaurante"),
    "LA AMERICANA":         ("ALIMENTACION", "Restaurante"),
    "TU OTRO YO":           ("ALIMENTACION", "Restaurante"),
    "LOS ROLES":            ("ALIMENTACION", "Restaurante"),
    "PAN BUENO":            ("CAFE/PAN", "Pan"),
    "FOCACCIA":             ("CAFE/PAN", "Pan"),
    "EL CANTON":            ("ALIMENTACION", "Restaurante"),
    "TOKS":                 ("ALIMENTACION", "Restaurante"),
    "OPER A Y B":           ("ALIMENTACION", "Restaurante"),
    "TOMATE TAQUERIA":      ("ALIMENTACION", "Restaurante"),
    "KK AV CIRCUNVALACION": ("ALIMENTACION", "Restaurante"),
    "FS VILLAHERMOSA":      ("ALIMENTACION", "Restaurante"),
    "MISION GUADALAJARA":   ("ALIMENTACION", "Restaurante"),
    "BUONISSIMO":           ("ALIMENTACION", "Restaurante"),
    "CLIP MX SERV DAYLA":   ("ALIMENTACION", "Restaurante"),
    "CONSUMO CASHLESS":     ("OCIO", "Eventos y congresos"),
    "AL MERAJ":             ("ALIMENTACION", "Restaurante"),
    "CHOQUITA":             ("ALIMENTACION", "Restaurante"),
    "FLOR DE CORDOBA":      ("ALIMENTACION", "Restaurante"),
    "MI LINDO NAYARIT":     ("ALIMENTACION", "Restaurante"),
    "MILANO":               ("ALIMENTACION", "Restaurante"),
    "PA CHANGUITOS":        ("ALIMENTACION", "Restaurante"),
    "MISC COTIDIANO":       ("ALIMENTACION", "Restaurante"),
    "MAYSON KAY":           ("ALIMENTACION", "Restaurante"),
    "CONT BUSCORGIO":       ("ALIMENTACION", "Restaurante"),
    "SMM_":                 ("ALIMENTACION", "Restaurante"),
    "ELEVEN":               ("ALIMENTACION", "Conveniencia"),
    "LIV GDL":              ("ROPA", "Ropa"),
    "LIV ":                 ("ROPA", "Ropa"),
    "ITX R LEF":            ("ROPA", "Ropa"),
    "MERPAGO ROSEBYROSE":   ("ROPA", "Ropa"),
    "TDA REG NIHAOMERCADO": ("VIVIENDA", "Artículos del hogar"),
    "CLIP MX TDA GG BALLOON":("VIVIENDA", "Artículos del hogar"),
    "C A VIL":              ("DIGITAL", "Suscripciones entretenimiento"),
    "TCONE AGREGADOR":      ("ALIMENTACION", "Conveniencia"),
    "FLP AVILA":            ("ALIMENTACION", "Conveniencia"),
    "074 PATRIA":           ("ALIMENTACION", "Conveniencia"),
    "ATTAPP MICROS":        ("DIGITAL", "Celular"),
    "MI ATT A APP":         ("DIGITAL", "Celular"),
    "FRESKO":               ("ALIMENTACION", "Súper"),
    "SORIANA":              ("ALIMENTACION", "Súper"),
    "WALMART":              ("ALIMENTACION", "Súper"),
    "WAL MART":             ("ALIMENTACION", "Súper"),
    "COSTCO":               ("ALIMENTACION", "Súper"),
    "CHEDRAUI":             ("ALIMENTACION", "Súper"),
    "BODEGA AURRERA":       ("ALIMENTACION", "Súper"),
    "BODEGA GUAD":          ("ALIMENTACION", "Súper"),
    "BGA AURRERA":          ("ALIMENTACION", "Súper"),
    "LA COMER":             ("ALIMENTACION", "Súper"),
    "HEB":                  ("ALIMENTACION", "Súper"),
    "SUPERAMA":             ("ALIMENTACION", "Súper"),
    "ABARR":                ("ALIMENTACION", "Súper"),
    "SUPER LA PLAYA":       ("ALIMENTACION", "Súper"),
    "SUPER KM 10":          ("ALIMENTACION", "Súper"),
    "MAXISUPER":            ("ALIMENTACION", "Súper"),
    "SUPERCENTER":          ("ALIMENTACION", "Súper"),
    "TDAS S RUIZ":          ("ALIMENTACION", "Súper"),
    "F AHORRO":             ("ALIMENTACION", "Súper"),
    "WM EXPRESS":           ("ALIMENTACION", "Súper"),
    "F 178 AVILA":          ("ALIMENTACION", "Súper"),
    "F 155 FLORENCIA":      ("ALIMENTACION", "Súper"),
    "F191 CIRCUNVALACION":  ("ALIMENTACION", "Súper"),
    "OFFICE DEPOT":         ("ALIMENTACION", "Súper"),
    "OXXO GAS":             ("TRANSPORTE", "Gasolina"),
    "OXXO":                 ("ALIMENTACION", "Conveniencia"),
    "7-ELEV":               ("ALIMENTACION", "Conveniencia"),
    "7 ELEVEN":             ("ALIMENTACION", "Conveniencia"),
    "7ELEVEN":              ("ALIMENTACION", "Conveniencia"),
    "GAS SAN MIGUEL":       ("TRANSPORTE", "Gasolina"),
    "SERV COUNTRY":         ("TRANSPORTE", "Gasolina"),
    "GAS KINZA":            ("TRANSPORTE", "Gasolina"),
    "KINZA SAN MIGUEL":     ("TRANSPORTE", "Gasolina"),
    "SERV GASORO":          ("TRANSPORTE", "Gasolina"),
    "SERV LA PAZ":          ("TRANSPORTE", "Gasolina"),
    "SERV PATRIA":          ("TRANSPORTE", "Gasolina"),
    "GAS COMBUST":          ("TRANSPORTE", "Gasolina"),
    "GAS ADOLF":            ("TRANSPORTE", "Gasolina"),
    "GASOL":                ("TRANSPORTE", "Gasolina"),
    "GAVIOTAS":             ("TRANSPORTE", "Gasolina"),
    "SERV REGIO":           ("TRANSPORTE", "Gasolina"),
    "PEMEX":                ("TRANSPORTE", "Gasolina"),
    "NETPAY GAS SERV":      ("TRANSPORTE", "Gasolina"),
    "SERVIFACIL":           ("TRANSPORTE", "Gasolina"),
    "AUTOZONE":             ("TRANSPORTE", "Mantenimiento auto"),
    "TALLER ERICKS":        ("TRANSPORTE", "Mantenimiento auto"),
    "PAYCLIP MEC TRANSCLIM":("TRANSPORTE", "Mantenimiento auto"),
    "CLIP MX MEC ZEPELIN":  ("TRANSPORTE", "Mantenimiento auto"),
    "RECAUDADORA":          ("TRANSPORTE", "Mantenimiento auto"),
    "TEMU":                 ("VIVIENDA", "Artículos del hogar"),
    "CRISTAL":              ("VIVIENDA", "Artículos del hogar"),
    "MONARCA":              ("VIVIENDA", "Artículos del hogar"),
    "MINISO":               ("VIVIENDA", "Artículos del hogar"),
    "TIENDA OBSERVATORIO":  ("VIVIENDA", "Artículos del hogar"),
    "VIVOINTERIOR":         ("VIVIENDA", "Artículos del hogar"),
    "FLORERIA":             ("FAMILIA_REGALOS", "Regalos"),
    "ZTL VIVO":             ("VIVIENDA", "Artículos del hogar"),
    "ZTL ROMA":             ("VIVIENDA", "Artículos del hogar"),
    "PLASTIGLOBOS":         ("VIVIENDA", "Artículos del hogar"),
    "FERRETERIA":           ("VIVIENDA", "Artículos del hogar"),
    "FERR IDEA":            ("VIVIENDA", "Artículos del hogar"),
    "TLAPALERIA":           ("VIVIENDA", "Artículos del hogar"),
    "CFE":                  ("VIVIENDA", "Luz"),
    "IKEA":                 ("VIVIENDA", "Artículos del hogar"),
    "DHL":                  ("VIVIENDA", "Artículos del hogar"),
    "ESTAFETA":             ("VIVIENDA", "Artículos del hogar"),
    "MAC STORE":            ("TECH/DIGITAL", "Deudas MSI"),
    "MACSTORE":             ("TECH/DIGITAL", "Deudas MSI"),
    "MERPAGO MACSTORE":     ("TECH/DIGITAL", "Deudas MSI"),
    "APPLE.COM/BILL":       ("DIGITAL", "Suscripciones entretenimiento"),
    "APPLE":                ("DIGITAL", "Suscripciones IA/productividad"),
    "STR AMAZON":           ("DIGITAL", "Accesorios tech"),
    "AMAZON PRIME":         ("DIGITAL", "Suscripciones entretenimiento"),
    "AMAZONPRIMESUBS":      ("DIGITAL", "Suscripciones entretenimiento"),
    "AMAZON":               ("DIGITAL", "Accesorios tech"),
    "GITHUB":               ("DIGITAL", "Suscripciones IA/productividad"),
    "COMP DDTECH":          ("DIGITAL", "Accesorios tech"),
    "RAILWAY":              ("PROYECTOS", "Hosting"),
    "NETFLIX":              ("DIGITAL", "Suscripciones entretenimiento"),
    "SPOTIFY":              ("DIGITAL", "Suscripciones entretenimiento"),
    "HBO":                  ("DIGITAL", "Suscripciones entretenimiento"),
    "DISNEY":               ("DIGITAL", "Suscripciones entretenimiento"),
    "TOTALPLAY":            ("VIVIENDA", "Internet"),
    "TOTAL PLAY CR MEX":   ("VIVIENDA", "Internet"),
    "TOTAL PLAY":           ("VIVIENDA", "Internet"),
    "IZZI":                 ("VIVIENDA", "Internet"),
    "TELMEX":               ("VIVIENDA", "Internet"),
    "TELCEL":               ("DIGITAL", "Celular"),
    "QOBUZ":                ("DIGITAL", "Suscripciones entretenimiento"),
    "CUBAMUSIC":            ("DIGITAL", "Suscripciones entretenimiento"),
    "CANVA":                ("DIGITAL", "Suscripciones IA/productividad"),
    "CLAUDE":               ("DIGITAL", "Suscripciones IA/productividad"),
    "GOOGLE":               ("DIGITAL", "Suscripciones IA/productividad"),
    "MERPAGO TELEFONIA":    ("DIGITAL", "Celular"),
    "D LOCAL ZETY":         ("DIGITAL", "Suscripciones entretenimiento"),
    "OPENPAY ZETYCOM":      ("DIGITAL", "Suscripciones entretenimiento"),
    "OPENPAY LANK":         ("DIGITAL", "Suscripciones entretenimiento"),
    "STR PARCO APP":        ("DIGITAL", "Suscripciones entretenimiento"),
    "STR ZAINE ROSABAL":    ("DIGITAL", "Suscripciones entretenimiento"),
    "GPO ZETA WEB":         ("DIGITAL", "Suscripciones entretenimiento"),
    "DP 11020":             ("DIGITAL", "Suscripciones entretenimiento"),
    "DP 11116":             ("DIGITAL", "Suscripciones entretenimiento"),
    "NAYAX1":               ("DIGITAL", "Suscripciones entretenimiento"),
    "STR AGREGADOR":        ("DIGITAL", "Suscripciones entretenimiento"),
    "JAL SMART":            ("DIGITAL", "Suscripciones entretenimiento"),
    "LIVERPOOL":            ("ROPA", "Ropa"),
    "ELPALACIOHIERRO":      ("ROPA", "Ropa"),
    "HM MX":                ("ROPA", "Ropa"),
    "NIKE":                 ("ROPA", "Ropa deportiva"),
    "INNVICTUS":            ("ROPA", "Ropa deportiva"),
    "MILAN TOJOS":          ("ROPA", "Ropa deportiva"),
    "BOUT SPF":             ("ROPA", "Ropa"),
    "CALZADO":              ("ROPA", "Calzado"),
    "FARMACIA":             ("SALUD", "Farmacia"),
    "FARM ":                ("SALUD", "Farmacia"),
    "BENAVIDES":            ("SALUD", "Farmacia"),
    "SIMILARES":            ("SALUD", "Farmacia"),
    "FCIA ":                ("SALUD", "Farmacia"),
    "YZA PLUS":             ("SALUD", "Farmacia"),
    "BPK CLIN FARMA":       ("SALUD", "Farmacia"),
    "BP MISC ALTA PROT":    ("SALUD", "Farmacia"),
    "MEDIC":                ("SALUD", "Consultas"),
    "DOCTOR":               ("SALUD", "Consultas"),
    "CLINICA":              ("SALUD", "Consultas"),
    "HOSPITAL":             ("SALUD", "Consultas"),
    "DRA ANNAMARIA":        ("SALUD", "Consultas"),
    "ORG SALUD":            ("SALUD", "Consultas"),
    "ESTUD CLIN":           ("SALUD", "Estudios"),
    "CHOPO":                ("SALUD", "Estudios"),
    "DIDI":                 ("TRANSPORTE", "Taxi/apps"),
    "UBER":                 ("TRANSPORTE", "Taxi/apps"),
    "ATTA TAXIS":           ("TRANSPORTE", "Taxi/apps"),
    "OP AIREPAZ":           ("TRANSPORTE", "Taxi/apps"),
    "PRIMERA PLUS":         ("TRANSPORTE", "Taxi/apps"),
    "AUTOTRANSP AER":       ("TRANSPORTE", "Taxi/apps"),
    "ACO MEX APTO":         ("TRANSPORTE", "Taxi/apps"),
    "CINEPOLIS":            ("OCIO", "Cine"),
    "BOLICHE":              ("OCIO", "Salidas"),
    "AFRICAM":              ("OCIO", "Salidas"),
    "PARQUE AFRICAM":       ("OCIO", "Salidas"),
    "PQUE AFRICAM":         ("OCIO", "Salidas"),
    "PARQUE SENDELA":       ("OCIO", "Salidas"),
    "TEQUILA GRAND TOUR":   ("OCIO", "Salidas"),
    "INAH":                 ("OCIO", "Salidas"),
    "CLUB DEP GOLF":        ("OCIO", "Salidas"),
    "BOLETOMOVIL":          ("OCIO", "Eventos y congresos"),
    "BOLETO MOVIL":         ("OCIO", "Eventos y congresos"),
    "MERCADOPAGO BOLETOMO": ("OCIO", "Eventos y congresos"),
    "HANGAR UNIVERSIDAD":   ("OCIO", "Salidas"),
    "EL BAR 2":             ("OCIO", "Salidas"),
    "BAR BAUCHERA":         ("OCIO", "Salidas"),
    "BAR OBSERVATORIO":     ("OCIO", "Salidas"),
    "CERV DLA COSTA":       ("OCIO", "Salidas"),
    "CENTRO CONSUMO 2":     ("OCIO", "Salidas"),
    "ALOHA":                ("OCIO", "Salidas"),
    "CANTARITOS":           ("OCIO", "Salidas"),
    "SALSA":                ("SALSA", "Clases"),
    "BACHATA":              ("SALSA", "Clases"),
    "DANCE":                ("SALSA", "Clases"),
    "MAMA RUMBA":           ("SALSA", "Social"),
    "MALAMBA":              ("SALSA", "Social"),
    "STARBUCKS":            ("CAFE/PAN", "Café"),
    "NESPRESSO":            ("CAFE/PAN", "Café"),
    "COFFEE":               ("CAFE/PAN", "Café"),
    "CAFE":                 ("CAFE/PAN", "Café"),
    "VIGO COFFEE":          ("CAFE/PAN", "Café"),
    "UDEMY":                ("APRENDIZAJE", "Cursos"),
    "COURSERA":             ("APRENDIZAJE", "Cursos"),
    "DATACAMP":             ("APRENDIZAJE", "Cursos"),
    "BUSUU":                ("APRENDIZAJE", "Cursos"),
    "LIBRO":                ("APRENDIZAJE", "Libros"),
    "GANDHI":               ("APRENDIZAJE", "Libros"),
    "CLIPMX SPARK":         ("APRENDIZAJE", "Papelería"),
    "PAYCLIP LIB SPARK":    ("APRENDIZAJE", "Papelería"),
    "VOLARIS":              ("VIAJES", "Transporte"),
    "AEROMEXICO":           ("VIAJES", "Transporte"),
    "AEROBUS":              ("VIAJES", "Transporte"),
    "VIVA AEROBUS":         ("VIAJES", "Transporte"),
    "AIRBNB":               ("VIAJES", "Hospedaje"),
    "HOTEL":                ("VIAJES", "Hospedaje"),
    "QUINTA EDEN":          ("VIAJES", "Hospedaje"),
    "FACEBK":               ("PROYECTOS", "Publicidad"),
    "FACEBOOK":             ("PROYECTOS", "Publicidad"),
    "META":                 ("PROYECTOS", "Publicidad"),
    "INDEED":               ("PROYECTOS", "Reclutamiento"),
    "FIBRA":                ("INVERSION", "Inversión"),
    "CETES":                ("INVERSION", "Inversión"),
    "GBM":                  ("INVERSION", "Inversión"),
    "BITSO":                ("INVERSION", "Crypto"),
    "REGALO":               ("FAMILIA_REGALOS", "Regalos"),
    "GIFT":                 ("FAMILIA_REGALOS", "Regalos"),
    "PENALIZACION":         ("COSTOS_FINANCIEROS", "Penalizaciones"),
    "INTERESES":            ("COSTOS_FINANCIEROS", "Intereses"),
    "IVA SOBRE COMISIONES": ("COSTOS_FINANCIEROS", "Comisiones"),
    "CON INTERES PAGO":     ("COSTOS_FINANCIEROS", "Intereses"),
    "CARGO POR TRASPASO":   ("COSTOS_FINANCIEROS", "Comisiones"),
    "PAGOS INTERBANCARIOS": ("PAGO_TDC", ""),
    "BBV CAJERO":           ("FINANZAS", "Retiro efectivo"),
}

SUBCATEGORIAS: dict[str, list[str]] = {
    "ALIMENTACION":      ["Súper", "Conveniencia", "Delivery", "Restaurante", "Fast Food"],
    "APRENDIZAJE":       ["Cursos", "Libros", "Papelería"],
    "CAFE/PAN":          ["Café", "Pan"],
    "COSTOS_FINANCIEROS":["Intereses", "Comisiones", "Penalizaciones"],
    "CUIDADO_PERSONAL":  ["Barbería", "Higiene"],
    "DEPORTE":           ["Gym", "Fútbol", "Equipo"],
    "DIGITAL":           ["Celular", "Suscripciones IA/productividad", "Suscripciones entretenimiento", "Accesorios tech"],
    "FAMILIA_REGALOS":   ["Regalos", "Apoyo familiar", "Colectas"],
    "FINANZAS":          ["Deudas MSI", "Cargos bancarios", "Transferencia", "Retiro efectivo", "Reembolsable", "Pago servicios"],
    "INVERSION":         ["Ahorro", "Inversión", "Crypto", "Fondo viaje", "Fondo emergencias"],
    "NOMINA":            ["Pago nominal", "Bono"],
    "OCIO":              ["Eventos y congresos", "Cine", "Salidas", "Videojuegos"],
    "OTROS":             [""],
    "PRESTAMOS":         ["Prestado", "Cobrado"],
    "PROYECTOS":         ["Publicidad", "Hosting", "Software", "Reclutamiento"],
    "ROPA":              ["Ropa", "Calzado", "Ropa deportiva"],
    "SALSA":             ["Clases", "Congreso", "Social", "Taller", "App"],
    "SALUD":             ["Consultas", "Farmacia", "Estudios"],
    "TECH/DIGITAL":      ["Deudas MSI", "Accesorios", "Software"],
    "TRANSPORTE":        ["Gasolina", "Seguro auto", "Mantenimiento auto", "Taxi/apps", "Estacionamiento"],
    "VIAJES":            ["Transporte", "Hospedaje", "Comida", "Otros"],
    "VIVIENDA":          ["Renta", "Aportación renta", "Luz", "Agua", "Gas", "Internet", "Artículos del hogar", "Lavandería", "Mudanza"],
}

BLACKLIST = [
    "NOTAS:", "VER NOTAS", "TOTAL CARGOS", "TOTAL ABONOS",
    "NUMERO DE CUENTA", "TARJETA TITULAR", "TARJETA DIGITAL",
    "FECHA DE LA", "FECHA DE CARGO", "DESCRIPCION DEL", "DESCRIPCI",
    "IVA :", "TIPO DE CAMBIO", "MXP $",
    "CAPITAL:", "PAGO EXCEDENTE", "INTERES:", "COMISIONES:",
    "PAGINA", "NUMERO DE CUENTA",
]

MSI_START = [
    "COMPRAS Y CARGOS DIFERIDOS A MESES SIN INTERESES",
    "CARGOS DIFERIDOS A MESES",
    "A) COMPRAS Y CARGOS DIFERIDOS",
]
MSI_END = [
    "CARGOS,COMPRAS Y ABONOS REGULARES",
    "CARGOS, ABONOS Y COMPRAS REGULARES",
    "COMPRAS Y CARGOS REGULARES",
    "B) CARGOS, ABONOS",
    "C) CARGOS, ABONOS",
    "TARJETA DIGITAL",
    "TDC DIGITAL",
]


def get_categoria_subcategoria(descripcion: str, custom_kw: dict | None = None) -> tuple[str, str]:
    desc = descripcion.upper()
    if custom_kw:
        for kw, (cat, subcat) in custom_kw.items():
            if kw in desc:
                return cat, subcat
    for keyword, (cat, subcat) in CATEGORIAS.items():
        if keyword.upper() in desc:
            return cat, subcat
    return "OTROS", ""
