"""
Shared config for the Estados de Cuenta module.
Mirrors SG_CREDIT_CARD_PROJECT/config.py — kept here so Eudaimonia has no
dependency on the SG project being present (works standalone on Railway).
"""
import os

PDF_PASSWORD      = os.environ.get("PDF_PASSWORD", "")
PDF_PASSWORD_BBVA = os.environ.get("PDF_PASSWORD_BBVA", "")

MESES = {
    "ene": "01", "feb": "02", "mar": "03", "abr": "04",
    "may": "05", "jun": "06", "jul": "07", "ago": "08",
    "sep": "09", "oct": "10", "nov": "11", "dic": "12",
    "jan": "01", "apr": "04", "aug": "08", "dec": "12",
}

CATEGORIAS: dict[str, tuple[str, str]] = {
    "BURGER":               ("COMIDA/REST", "Restaurante"),
    "KFC":                  ("COMIDA/REST", "Restaurante"),
    "LITTLE CAESAR":        ("COMIDA/REST", "Restaurante"),
    "SUBWAY":               ("COMIDA/REST", "Restaurante"),
    "RESTAURANT":           ("COMIDA/REST", "Restaurante"),
    "TACO":                 ("COMIDA/REST", "Restaurante"),
    "VIPS":                 ("COMIDA/REST", "Restaurante"),
    "RAPPI":                ("COMIDA/REST", "Delivery"),
    "CARLS JR":             ("COMIDA/REST", "Delivery"),
    "DOMINO":               ("COMIDA/REST", "Delivery"),
    "WINGSTOP":             ("COMIDA/REST", "Delivery"),
    "MCDONALDS":            ("COMIDA/REST", "Delivery"),
    "COM RAP":              ("COMIDA/REST", "Delivery"),
    "BPK FASTFOOD":         ("COMIDA/REST", "Delivery"),
    "BUGALO":               ("COMIDA/REST", "Restaurante"),
    "KIMODO":               ("COMIDA/REST", "Restaurante"),
    "MERPAGO REST":         ("COMIDA/REST", "Restaurante"),
    "LOSWEROS":             ("COMIDA/REST", "Restaurante"),
    "PANADERIA":            ("COMIDA/REST", "Restaurante"),
    "PASTELES MARISA":      ("COMIDA/REST", "Restaurante"),
    "PAST MARISA":          ("COMIDA/REST", "Restaurante"),
    "CHILAQUILA":           ("COMIDA/REST", "Restaurante"),
    "SANTAROSALIA":         ("COMIDA/REST", "Restaurante"),
    "CAGUAMAS":             ("COMIDA/REST", "Restaurante"),
    "TOR PLANCHADAS":       ("COMIDA/REST", "Restaurante"),
    "ELGUERO":              ("COMIDA/REST", "Restaurante"),
    "3039 PSAN LUIS":       ("COMIDA/REST", "Restaurante"),
    "MERPAGO ARELLANO":     ("COMIDA/REST", "Restaurante"),
    "MERPAGO AGREGADOR":    ("COMIDA/REST", "Restaurante"),
    "MERPAGO ASADAS":       ("COMIDA/REST", "Restaurante"),
    "MERPAGO LOSVOLCANES":  ("COMIDA/REST", "Restaurante"),
    "MERPAGO LOSVOLCAM":    ("COMIDA/REST", "Restaurante"),
    "MERPAGO LOSCUATES":    ("COMIDA/REST", "Restaurante"),
    "MERPAGO ELREY":        ("COMIDA/REST", "Restaurante"),
    "MERPAGO ELBIGOTES":    ("COMIDA/REST", "Restaurante"),
    "MERPAGO TAQUERIA":     ("COMIDA/REST", "Restaurante"),
    "MERPAGO CORTIJO":      ("COMIDA/REST", "Restaurante"),
    "MERPAGO DANI":         ("COMIDA/REST", "Restaurante"),
    "MERPAGO FAMILIALOSWER":("COMIDA/REST", "Restaurante"),
    "MERPAGO TIENDACHARLY": ("COMIDA/REST", "Restaurante"),
    "MERPAGO NOVEDADESLIA": ("COMIDA/REST", "Restaurante"),
    "MERPAGO VAMPIROS":     ("COMIDA/REST", "Restaurante"),
    "MERPAGO AMANDEL":      ("COMIDA/REST", "Restaurante"),
    "MERPAGO KOLOMITOS":    ("COMIDA/REST", "Restaurante"),
    "MERPAGO BBFLORES":     ("COMIDA/REST", "Restaurante"),
    "MERPAGO LABAOZERIAGDL":("COMIDA/REST", "Restaurante"),
    "MERPAGO PACHANGUITOS": ("COMIDA/REST", "Restaurante"),
    "MERPAGO CREPASTERRAN": ("COMIDA/REST", "Restaurante"),
    "MERPAGO CHOCLOYMAIZ":  ("COMIDA/REST", "Restaurante"),
    "MERPAGO QUEENLATINCLU":("SUSCRIPCIONES", "Música"),
    "MERCADO PAGO":         ("COMIDA/REST", "Restaurante"),
    "MERCADOPAGO LOSVOLCA": ("COMIDA/REST", "Restaurante"),
    "POINTMP DONFREDY":     ("COMIDA/REST", "Restaurante"),
    "POINTMP ASADAS":       ("COMIDA/REST", "Restaurante"),
    "POINTMP ALIMENTOS":    ("COMIDA/REST", "Restaurante"),
    "POINTMP ARELLANO":     ("COMIDA/REST", "Restaurante"),
    "POINTMP CREPASTERRAN": ("COMIDA/REST", "Restaurante"),
    "POINTMP FAMILIALOSWER":("COMIDA/REST", "Restaurante"),
    "POINTMP TIENDACHARLY": ("COMIDA/REST", "Restaurante"),
    "POINTMP SERENAMORENA": ("COMIDA/REST", "Restaurante"),
    "POINTMP JUAN":         ("COMIDA/REST", "Restaurante"),
    "POINTMP TAQUERIA":     ("COMIDA/REST", "Restaurante"),
    "POINTMP MEMELOPOLIS":  ("COMIDA/REST", "Restaurante"),
    "POINTMP QUEENLATINCLU":("SUSCRIPCIONES", "Música"),
    "POINTMP PUNTOCASINO":  ("SALSA", "Evento"),
    "NETPAY TAQUERIA":      ("COMIDA/REST", "Restaurante"),
    "NETPAY LOS TARASCOS":  ("COMIDA/REST", "Restaurante"),
    "NETPAY EL REY":        ("COMIDA/REST", "Restaurante"),
    "PAYCLIP REST":         ("COMIDA/REST", "Restaurante"),
    "PAYCLIP GIRO":         ("COMIDA/REST", "Restaurante"),
    "CLIP MX REST":         ("COMIDA/REST", "Restaurante"),
    "BZPAYMX EL CANTON":    ("COMIDA/REST", "Restaurante"),
    "ABTS MARCELLA":        ("COMIDA/REST", "Restaurante"),
    "ABTS CMT":             ("COMIDA/REST", "Restaurante"),
    "ABTS 12480":           ("COMIDA/REST", "Restaurante"),
    "1305 MIDTOWN":         ("COMIDA/REST", "Restaurante"),
    "REST ":                ("COMIDA/REST", "Restaurante"),
    "PIZZERIA":             ("COMIDA/REST", "Restaurante"),
    "PIZZA":                ("COMIDA/REST", "Restaurante"),
    "TAQUERIA":             ("COMIDA/REST", "Restaurante"),
    "HAMBURGUESAS":         ("COMIDA/REST", "Restaurante"),
    "CARNITAS":             ("COMIDA/REST", "Restaurante"),
    "KARNITAS":             ("COMIDA/REST", "Restaurante"),
    "BIRRIA":               ("COMIDA/REST", "Restaurante"),
    "TRATTORIA":            ("COMIDA/REST", "Restaurante"),
    "RAMEN":                ("COMIDA/REST", "Restaurante"),
    "CHURROS":              ("COMIDA/REST", "Restaurante"),
    "TORTAS":               ("COMIDA/REST", "Restaurante"),
    "PESCADERIA":           ("COMIDA/REST", "Restaurante"),
    "CREPERIA":             ("COMIDA/REST", "Restaurante"),
    "PASTELERIA":           ("COMIDA/REST", "Restaurante"),
    "GORDITAS":             ("COMIDA/REST", "Restaurante"),
    "CARNES ":              ("COMIDA/REST", "Restaurante"),
    "CARNES ASADAS":        ("COMIDA/REST", "Restaurante"),
    "LA PARROQUIA":         ("COMIDA/REST", "Restaurante"),
    "DAIRY QUEEN":          ("COMIDA/REST", "Restaurante"),
    "MOSHI MOSHI":          ("COMIDA/REST", "Restaurante"),
    "YOGOCUP":              ("COMIDA/REST", "Restaurante"),
    "ESPIRAL LAVITOLA":     ("COMIDA/REST", "Restaurante"),
    "SAINT MICHEL":         ("COMIDA/REST", "Café"),
    "MAISON KAYSER":        ("COMIDA/REST", "Café"),
    "PLAZA PANAMERICANA":   ("COMIDA/REST", "Restaurante"),
    "HATO":                 ("COMIDA/REST", "Restaurante"),
    "LA TIZNADA":           ("COMIDA/REST", "Restaurante"),
    "LA AMERICANA":         ("COMIDA/REST", "Restaurante"),
    "TU OTRO YO":           ("COMIDA/REST", "Restaurante"),
    "LOS ROLES":            ("COMIDA/REST", "Restaurante"),
    "PAN BUENO":            ("COMIDA/REST", "Restaurante"),
    "FOCACCIA":             ("COMIDA/REST", "Restaurante"),
    "EL CANTON":            ("COMIDA/REST", "Restaurante"),
    "TOKS":                 ("COMIDA/REST", "Restaurante"),
    "OPER A Y B":           ("COMIDA/REST", "Restaurante"),
    "TOMATE TAQUERIA":      ("COMIDA/REST", "Restaurante"),
    "KK AV CIRCUNVALACION": ("COMIDA/REST", "Restaurante"),
    "FS VILLAHERMOSA":      ("COMIDA/REST", "Restaurante"),
    "MISION GUADALAJARA":   ("COMIDA/REST", "Restaurante"),
    "BUONISSIMO":           ("COMIDA/REST", "Restaurante"),
    "CLIP MX SERV DAYLA":   ("COMIDA/REST", "Restaurante"),
    "CONSUMO CASHLESS":     ("ENTRETENIMIENTO", "Eventos"),
    "AL MERAJ":             ("COMIDA/REST", "Restaurante"),
    "CHOQUITA":             ("COMIDA/REST", "Restaurante"),
    "FLOR DE CORDOBA":      ("COMIDA/REST", "Restaurante"),
    "MI LINDO NAYARIT":     ("COMIDA/REST", "Restaurante"),
    "MILANO":               ("COMIDA/REST", "Restaurante"),
    "PA CHANGUITOS":        ("COMIDA/REST", "Restaurante"),
    "MISC COTIDIANO":       ("COMIDA/REST", "Restaurante"),
    "MAYSON KAY":           ("COMIDA/REST", "Restaurante"),
    "CONT BUSCORGIO":       ("COMIDA/REST", "Restaurante"),
    "SMM_":                 ("COMIDA/REST", "Restaurante"),
    "ELEVEN":               ("VIVERES/SUPER", "Conveniencia"),
    "LIV GDL":              ("ROPA", "Ropa"),
    "LIV ":                 ("ROPA", "Ropa"),
    "ITX R LEF":            ("ROPA", "Ropa"),
    "MERPAGO ROSEBYROSE":   ("ROPA", "Ropa"),
    "TDA REG NIHAOMERCADO": ("CASA/HOGAR", "Hogar general"),
    "CLIP MX TDA GG BALLOON":("CASA/HOGAR", "Decoración"),
    "C A VIL":              ("SUSCRIPCIONES", "Música"),
    "TCONE AGREGADOR":      ("VIVERES/SUPER", "Conveniencia"),
    "FLP AVILA":            ("VIVERES/SUPER", "Conveniencia"),
    "074 PATRIA":           ("VIVERES/SUPER", "Conveniencia"),
    "ATTAPP MICROS":        ("SERVICIOS", "Saldo telefono"),
    "MI ATT A APP":         ("SERVICIOS", "Saldo telefono"),
    "FRESKO":               ("VIVERES/SUPER", "Supermercado"),
    "SORIANA":              ("VIVERES/SUPER", "Supermercado"),
    "WALMART":              ("VIVERES/SUPER", "Supermercado"),
    "WAL MART":             ("VIVERES/SUPER", "Supermercado"),
    "COSTCO":               ("VIVERES/SUPER", "Supermercado"),
    "CHEDRAUI":             ("VIVERES/SUPER", "Supermercado"),
    "BODEGA AURRERA":       ("VIVERES/SUPER", "Supermercado"),
    "BODEGA GUAD":          ("VIVERES/SUPER", "Supermercado"),
    "BGA AURRERA":          ("VIVERES/SUPER", "Supermercado"),
    "LA COMER":             ("VIVERES/SUPER", "Supermercado"),
    "HEB":                  ("VIVERES/SUPER", "Supermercado"),
    "SUPERAMA":             ("VIVERES/SUPER", "Supermercado"),
    "ABARR":                ("VIVERES/SUPER", "Supermercado"),
    "SUPER LA PLAYA":       ("VIVERES/SUPER", "Supermercado"),
    "SUPER KM 10":          ("VIVERES/SUPER", "Supermercado"),
    "MAXISUPER":            ("VIVERES/SUPER", "Supermercado"),
    "SUPERCENTER":          ("VIVERES/SUPER", "Supermercado"),
    "TDAS S RUIZ":          ("VIVERES/SUPER", "Supermercado"),
    "F AHORRO":             ("VIVERES/SUPER", "Supermercado"),
    "WM EXPRESS":           ("VIVERES/SUPER", "Supermercado"),
    "F 178 AVILA":          ("VIVERES/SUPER", "Supermercado"),
    "F 155 FLORENCIA":      ("VIVERES/SUPER", "Supermercado"),
    "F191 CIRCUNVALACION":  ("VIVERES/SUPER", "Supermercado"),
    "OFFICE DEPOT":         ("VIVERES/SUPER", "Supermercado"),
    "OXXO GAS":             ("GASOLINA/AUTO", "Gasolina"),
    "OXXO":                 ("VIVERES/SUPER", "Conveniencia"),
    "7-ELEV":               ("VIVERES/SUPER", "Conveniencia"),
    "7 ELEVEN":             ("VIVERES/SUPER", "Conveniencia"),
    "7ELEVEN":              ("VIVERES/SUPER", "Conveniencia"),
    "GAS SAN MIGUEL":       ("GASOLINA/AUTO", "Gasolina"),
    "SERV COUNTRY":         ("GASOLINA/AUTO", "Gasolina"),
    "GAS KINZA":            ("GASOLINA/AUTO", "Gasolina"),
    "KINZA SAN MIGUEL":     ("GASOLINA/AUTO", "Gasolina"),
    "SERV GASORO":          ("GASOLINA/AUTO", "Gasolina"),
    "SERV LA PAZ":          ("GASOLINA/AUTO", "Gasolina"),
    "SERV PATRIA":          ("GASOLINA/AUTO", "Gasolina"),
    "GAS COMBUST":          ("GASOLINA/AUTO", "Gasolina"),
    "GAS ADOLF":            ("GASOLINA/AUTO", "Gasolina"),
    "GASOL":                ("GASOLINA/AUTO", "Gasolina"),
    "GAVIOTAS":             ("GASOLINA/AUTO", "Gasolina"),
    "SERV REGIO":           ("GASOLINA/AUTO", "Gasolina"),
    "PEMEX":                ("GASOLINA/AUTO", "Gasolina"),
    "NETPAY GAS SERV":      ("GASOLINA/AUTO", "Gasolina"),
    "AUTOZONE":             ("GASOLINA/AUTO", "Mantenimiento"),
    "TALLER ERICKS":        ("GASOLINA/AUTO", "Mantenimiento"),
    "PAYCLIP MEC TRANSCLIM":("GASOLINA/AUTO", "Mantenimiento"),
    "CLIP MX MEC ZEPELIN":  ("GASOLINA/AUTO", "Mantenimiento"),
    "RECAUDADORA":          ("GASOLINA/AUTO", "Tenencia & Trámites"),
    "TEMU":                 ("CASA/HOGAR", "Hogar general"),
    "CRISTAL":              ("CASA/HOGAR", "Hogar general"),
    "MONARCA":              ("CASA/HOGAR", "Hogar general"),
    "MINISO":               ("CASA/HOGAR", "Hogar general"),
    "TIENDA OBSERVATORIO":  ("CASA/HOGAR", "Hogar general"),
    "VIVOINTERIOR":         ("CASA/HOGAR", "Decoración"),
    "FLORERIA":             ("CASA/HOGAR", "Decoración"),
    "ZTL VIVO":             ("CASA/HOGAR", "Decoración"),
    "ZTL ROMA":             ("CASA/HOGAR", "Decoración"),
    "PLASTIGLOBOS":         ("CASA/HOGAR", "Decoración"),
    "FERRETERIA":           ("CASA/HOGAR", "Mantenimiento"),
    "FERR IDEA":            ("CASA/HOGAR", "Mantenimiento"),
    "TLAPALERIA":           ("CASA/HOGAR", "Mantenimiento"),
    "CFE":                  ("SERVICIOS", "Luz"),
    "IKEA":                 ("CASA/HOGAR", "Muebles"),
    "DHL":                  ("CASA/HOGAR", "Envíos"),
    "ESTAFETA":             ("CASA/HOGAR", "Envíos"),
    "MAC STORE":            ("TECH/DIGITAL", "Deudas MSI"),
    "MACSTORE":             ("TECH/DIGITAL", "Deudas MSI"),
    "MERPAGO MACSTORE":     ("TECH/DIGITAL", "Deudas MSI"),
    "APPLE.COM/BILL":       ("SUSCRIPCIONES", "Digital"),
    "APPLE":                ("TECH/DIGITAL", "Software"),
    "STR AMAZON":           ("TECH/DIGITAL", "Accesorios"),
    "AMAZON PRIME":         ("SUSCRIPCIONES", "Streaming video"),
    "AMAZONPRIMESUBS":      ("SUSCRIPCIONES", "Streaming video"),
    "AMAZON":               ("TECH/DIGITAL", "Accesorios"),
    "GITHUB":               ("TECH/DIGITAL", "Software"),
    "COMP DDTECH":          ("TECH/DIGITAL", "Accesorios"),
    "NETFLIX":              ("SUSCRIPCIONES", "Streaming video"),
    "SPOTIFY":              ("SUSCRIPCIONES", "Música"),
    "HBO":                  ("SUSCRIPCIONES", "Streaming video"),
    "DISNEY":               ("SUSCRIPCIONES", "Streaming video"),
    "TOTALPLAY":            ("SERVICIOS", "Internet"),
    "TOTAL PLAY CR MEX":   ("SERVICIOS", "Internet"),
    "TOTAL PLAY":           ("SERVICIOS", "Internet"),
    "IZZI":                 ("SUSCRIPCIONES", "Internet/TV"),
    "TELMEX":               ("SUSCRIPCIONES", "Internet/TV"),
    "TELCEL":               ("SUSCRIPCIONES", "Telefonía"),
    "QOBUZ":                ("SUSCRIPCIONES", "Música"),
    "CUBAMUSIC":            ("SUSCRIPCIONES", "Música"),
    "CANVA":                ("SUSCRIPCIONES", "Diseño"),
    "CLAUDE":               ("SUSCRIPCIONES", "Productividad"),
    "GOOGLE":               ("SUSCRIPCIONES", "Productividad"),
    "MERPAGO TELEFONIA":    ("SUSCRIPCIONES", "Telefonía"),
    "D LOCAL ZETY":         ("SUSCRIPCIONES", "Digital"),
    "OPENPAY ZETYCOM":      ("SUSCRIPCIONES", "Digital"),
    "OPENPAY LANK":         ("SUSCRIPCIONES", "Digital"),
    "STR PARCO APP":        ("SUSCRIPCIONES", "Digital"),
    "STR ZAINE ROSABAL":    ("SUSCRIPCIONES", "Digital"),
    "GPO ZETA WEB":         ("SUSCRIPCIONES", "Digital"),
    "DP 11020":             ("SUSCRIPCIONES", "Digital"),
    "DP 11116":             ("SUSCRIPCIONES", "Digital"),
    "NAYAX1":               ("SUSCRIPCIONES", "Digital"),
    "STR AGREGADOR":        ("SUSCRIPCIONES", "Digital"),
    "JAL SMART":            ("SUSCRIPCIONES", "Digital"),
    "LIVERPOOL":            ("ROPA", "Ropa"),
    "ELPALACIOHIERRO":      ("ROPA", "Ropa"),
    "HM MX":                ("ROPA", "Ropa"),
    "NIKE":                 ("ROPA", "Ropa deportiva"),
    "INNVICTUS":            ("ROPA", "Ropa deportiva"),
    "MILAN TOJOS":          ("ROPA", "Ropa deportiva"),
    "BOUT SPF":             ("ROPA", "Ropa"),
    "CALZADO":              ("ROPA", "Calzado"),
    "FARMACIA":             ("SALUD", "Farmacia"),
    "FARM ":                ("SALUD", "Farmacia"),
    "BENAVIDES":            ("SALUD", "Farmacia"),
    "SIMILARES":            ("SALUD", "Farmacia"),
    "FCIA ":                ("SALUD", "Farmacia"),
    "YZA PLUS":             ("SALUD", "Farmacia"),
    "BPK CLIN FARMA":       ("SALUD", "Farmacia"),
    "BP MISC ALTA PROT":    ("SALUD", "Farmacia"),
    "MEDIC":                ("SALUD", "Médico"),
    "DOCTOR":               ("SALUD", "Médico"),
    "CLINICA":              ("SALUD", "Médico"),
    "HOSPITAL":             ("SALUD", "Médico"),
    "DRA ANNAMARIA":        ("SALUD", "Médico"),
    "ORG SALUD":            ("SALUD", "Médico"),
    "ESTUD CLIN":           ("SALUD", "Laboratorio"),
    "CHOPO":                ("SALUD", "Laboratorio"),
    "DIDI":                 ("TRANSPORTE", "Taxi"),
    "UBER":                 ("TRANSPORTE", "Taxi"),
    "ATTA TAXIS":           ("TRANSPORTE", "Taxi"),
    "OP AIREPAZ":           ("TRANSPORTE", "Taxi"),
    "PRIMERA PLUS":         ("TRANSPORTE", "Autobús"),
    "AUTOTRANSP AER":       ("TRANSPORTE", "Aeropuerto"),
    "ACO MEX APTO":         ("TRANSPORTE", "Aeropuerto"),
    "CINEPOLIS":            ("ENTRETENIMIENTO", "Cine"),
    "BOLICHE":              ("ENTRETENIMIENTO", "Salidas"),
    "AFRICAM":              ("ENTRETENIMIENTO", "Salidas"),
    "PARQUE AFRICAM":       ("ENTRETENIMIENTO", "Salidas"),
    "PQUE AFRICAM":         ("ENTRETENIMIENTO", "Salidas"),
    "PARQUE SENDELA":       ("ENTRETENIMIENTO", "Salidas"),
    "TEQUILA GRAND TOUR":   ("ENTRETENIMIENTO", "Salidas"),
    "INAH":                 ("ENTRETENIMIENTO", "Cultura"),
    "CLUB DEP GOLF":        ("ENTRETENIMIENTO", "Golf"),
    "BOLETOMOVIL":          ("ENTRETENIMIENTO", "Eventos"),
    "BOLETO MOVIL":         ("ENTRETENIMIENTO", "Eventos"),
    "MERCADOPAGO BOLETOMO": ("ENTRETENIMIENTO", "Eventos"),
    "HANGAR UNIVERSIDAD":   ("ENTRETENIMIENTO", "Bar & Antro"),
    "EL BAR 2":             ("ENTRETENIMIENTO", "Bar & Antro"),
    "BAR BAUCHERA":         ("ENTRETENIMIENTO", "Bar & Antro"),
    "BAR OBSERVATORIO":     ("ENTRETENIMIENTO", "Bar & Antro"),
    "CERV DLA COSTA":       ("ENTRETENIMIENTO", "Bar & Antro"),
    "CENTRO CONSUMO 2":     ("ENTRETENIMIENTO", "Bar & Antro"),
    "ALOHA":                ("ENTRETENIMIENTO", "Bar & Antro"),
    "CANTARITOS":           ("ENTRETENIMIENTO", "Bar & Antro"),
    "SALSA":                ("SALSA", "Clases"),
    "BACHATA":              ("SALSA", "Clases"),
    "DANCE":                ("SALSA", "Clases"),
    "MAMA RUMBA":           ("SALSA", "Evento"),
    "MALAMBA":              ("SALSA", "Evento"),
    "STARBUCKS":            ("CAFE/PAN", "Café"),
    "NESPRESSO":            ("CAFE/PAN", "Café"),
    "COFFEE":               ("CAFE/PAN", "Café"),
    "CAFE":                 ("CAFE/PAN", "Café"),
    "VIGO COFFEE":          ("CAFE/PAN", "Café"),
    "UDEMY":                ("APRENDIZAJE", "Cursos online"),
    "COURSERA":             ("APRENDIZAJE", "Cursos online"),
    "DATACAMP":             ("APRENDIZAJE", "Cursos online"),
    "BUSUU":                ("APRENDIZAJE", "Idiomas"),
    "LIBRO":                ("APRENDIZAJE", "Libros"),
    "GANDHI":               ("APRENDIZAJE", "Libros"),
    "CLIPMX SPARK":         ("APRENDIZAJE", "Papelería"),
    "PAYCLIP LIB SPARK":    ("APRENDIZAJE", "Papelería"),
    "VOLARIS":              ("VIAJES/VUELOS", "Vuelos"),
    "AEROMEXICO":           ("VIAJES/VUELOS", "Vuelos"),
    "AEROBUS":              ("VIAJES/VUELOS", "Vuelos"),
    "AIRBNB":               ("VIAJES/VUELOS", "Hotel"),
    "HOTEL":                ("VIAJES/VUELOS", "Hotel"),
    "QUINTA EDEN":          ("VIAJES/VUELOS", "Hotel"),
    "FACEBK":               ("PUBLICIDAD", "Meta Ads"),
    "FACEBOOK":             ("PUBLICIDAD", "Meta Ads"),
    "META":                 ("PUBLICIDAD", "Meta Ads"),
    "INDEED":               ("PUBLICIDAD", "Reclutamiento"),
    "FIBRA":                ("INVERSION", "Inversión"),
    "CETES":                ("INVERSION", "Inversión"),
    "GBM":                  ("INVERSION", "Inversión"),
    "BITSO":                ("INVERSION", "Crypto"),
    "REGALO":               ("REGALO", "General"),
    "GIFT":                 ("REGALO", "General"),
    "PENALIZACION":         ("FINANZAS", "Cargos bancarios"),
    "INTERESES":            ("FINANZAS", "Cargos bancarios"),
    "IVA SOBRE COMISIONES": ("FINANZAS", "Cargos bancarios"),
    "CON INTERES PAGO":     ("FINANZAS", "Cargos bancarios"),
    "CARGO POR TRASPASO":   ("FINANZAS", "Cargos bancarios"),
    "PAGOS INTERBANCARIOS": ("FINANZAS", "Transferencia"),
    "SERVIFACIL":           ("FINANZAS", "Transferencia"),
    "BBV CAJERO":           ("FINANZAS", "Retiro efectivo"),
}

SUBCATEGORIAS: dict[str, list[str]] = {
    "COMIDA/REST":     ["Restaurante", "Delivery", "Café"],
    "VIVERES/SUPER":   ["Supermercado", "Carnes", "Conveniencia", "Limpieza & Hogar"],
    "CASA/HOGAR":      ["Alquiler", "Luz", "Agua", "Gas", "Internet", "Decoración", "Muebles", "Mantenimiento", "Envíos", "Hogar general"],
    "GASOLINA/AUTO":   ["Gasolina", "Seguro", "Mantenimiento", "Tenencia & Trámites", "Uber/Aeropuerto"],
    "ROPA":            ["Ropa", "Calzado", "Ropa deportiva"],
    "SALUD":           ["Médico", "Farmacia", "Laboratorio"],
    "TECH/DIGITAL":    ["Deudas MSI", "Accesorios", "Software"],
    "SUSCRIPCIONES":   ["Streaming video", "Música", "Diseño", "Telefonía", "Internet/TV", "Productividad", "Digital", "Gym"],
    "ENTRETENIMIENTO": ["Bar & Antro", "Eventos", "Salidas", "Golf", "Cultura", "Cine"],
    "SALSA":           ["Clases", "Evento", "Congreso"],
    "VIAJES/VUELOS":   ["Vuelos", "Hotel", "Tours", "Transporte viaje"],
    "TRANSPORTE":      ["Taxi", "Aeropuerto", "Autobús"],
    "APRENDIZAJE":     ["Cursos online", "Idiomas", "Libros", "Papelería"],
    "PUBLICIDAD":      ["Meta Ads", "Reclutamiento", "Marketing digital"],
    "FINANZAS":        ["Deudas MSI", "Cargos bancarios", "Transferencia", "Retiro efectivo", "Reembolsable", "Pago servicios"],
    "INVERSION":       ["Ahorro", "Inversión", "Crypto", "Fondo viaje", "Fondo emergencias"],
    "CAFE/PAN":        ["Café", "Pan", "Social"],
    "GYM":             ["Membresía anual"],
    "DEPORTE":         ["Deporte general"],
    "REGALO":          ["General", "Cumpleaños", "Navidad", "Boda", "Flores"],
    "OTROS":           [""],
}

BLACKLIST = [
    "NOTAS:", "VER NOTAS", "TOTAL CARGOS", "TOTAL ABONOS",
    "NUMERO DE CUENTA", "TARJETA TITULAR", "TARJETA DIGITAL",
    "FECHA DE LA", "FECHA DE CARGO", "DESCRIPCION DEL", "DESCRIPCI",
    "IVA :", "TIPO DE CAMBIO", "MXP $",
    "CAPITAL:", "PAGO EXCEDENTE", "INTERES:", "COMISIONES:",
    "PAGINA", "NUMERO DE CUENTA",
]

MSI_START = [
    "COMPRAS Y CARGOS DIFERIDOS A MESES SIN INTERESES",
    "CARGOS DIFERIDOS A MESES",
    "A) COMPRAS Y CARGOS DIFERIDOS",
]
MSI_END = [
    "CARGOS,COMPRAS Y ABONOS REGULARES",
    "CARGOS, ABONOS Y COMPRAS REGULARES",
    "COMPRAS Y CARGOS REGULARES",
    "B) CARGOS, ABONOS",
    "C) CARGOS, ABONOS",
    "TARJETA DIGITAL",
    "TDC DIGITAL",
]


def get_categoria_subcategoria(descripcion: str, custom_kw: dict | None = None) -> tuple[str, str]:
    desc = descripcion.upper()
    if custom_kw:
        for kw, (cat, subcat) in custom_kw.items():
            if kw in desc:
                return cat, subcat
    for keyword, (cat, subcat) in CATEGORIAS.items():
        if keyword.upper() in desc:
            return cat, subcat
    return "OTROS", ""
