# Achievement definitions — pure data, no imports from this project.
#
# Each entry defines the achievement metadata and a condition function.
# condition(stats) -> bool, where stats is built by engine._gather_achievement_stats().
#
# stats keys:
#   streak, total_xp, total_coins, xp_week,
#   total_activity_count, cats_done_today (set), all_cats_ever (set),
#   prog_count, had_perfect_day, current_level

ACHIEVEMENT_DEFS = {
    "primer_paso": {
        "name":        "Primer Paso",
        "description": "Completa tu primera actividad",
        "icon":        "👣",
        "coins":       5,
        "xp":          10,
        "hidden":      False,
        "condition":   lambda s: s["total_activity_count"] >= 1,
    },
    "racha_7": {
        "name":        "Semana de Fuego",
        "description": "7 días consecutivos de actividad",
        "icon":        "🔥",
        "coins":       50,
        "xp":          60,
        "hidden":      True,
        "condition":   lambda s: s["streak"] >= 7,
    },
    "racha_10": {
        "name":        "Imparable",
        "description": "10 días consecutivos de actividad",
        "icon":        "⚡",
        "coins":       100,
        "xp":          100,
        "hidden":      True,
        "condition":   lambda s: s["streak"] >= 10,
    },
    "racha_21": {
        "name":        "Hábito Forjado",
        "description": "21 días consecutivos — el hábito ya es tuyo",
        "icon":        "💎",
        "coins":       250,
        "xp":          200,
        "hidden":      True,
        "condition":   lambda s: s["streak"] >= 21,
    },
    "racha_30": {
        "name":        "Modo Bestia",
        "description": "30 días consecutivos — nivel de élite absoluto",
        "icon":        "💀",
        "coins":       500,
        "xp":          400,
        "hidden":      True,
        "condition":   lambda s: s["streak"] >= 30,
    },
    "disciplina_total": {
        "name":        "Disciplina Total",
        "description": "Completa actividades de 5 o más categorías en un solo día",
        "icon":        "🎯",
        "coins":       100,
        "xp":          100,
        "hidden":      True,
        "condition":   lambda s: len(s["cats_done_today"]) >= 5,
    },
    "semana_elite": {
        "name":        "Semana Elite",
        "description": "Superar 200 XP en una semana",
        "icon":        "🏆",
        "coins":       150,
        "xp":          150,
        "hidden":      True,
        "condition":   lambda s: s["xp_week"] >= 200,
    },
    "programador_nato": {
        "name":        "Programador Nato",
        "description": "Completa 50 actividades de Programación",
        "icon":        "💻",
        "coins":       150,
        "xp":          150,
        "hidden":      True,
        "condition":   lambda s: s["prog_count"] >= 50,
    },
    "polimata": {
        "name":        "Polímata",
        "description": "Completa actividades de todas las categorías",
        "icon":        "🧠",
        "coins":       250,
        "xp":          200,
        "hidden":      True,
        "condition":   lambda s: len(s["all_cats_ever"]) >= 15,
    },
    "millonario": {
        "name":        "El Gran Inicio",
        "description": "Acumula 1000 coins en total",
        "icon":        "💰",
        "coins":       50,
        "xp":          50,
        "hidden":      True,
        "condition":   lambda s: s["total_coins"] >= 1000,
    },
    "perfeccionista": {
        "name":        "Perfeccionista",
        "description": "Completa un Día Perfecto (3 prioridades + 5+ pts de actividades)",
        "icon":        "✨",
        "coins":       75,
        "xp":          60,
        "hidden":      True,
        "condition":   lambda s: s["had_perfect_day"],
    },
    "nivel_5": {
        "name":        "Disciplinado",
        "description": "Alcanza el nivel 5",
        "icon":        "🎖️",
        "coins":       200,
        "xp":          0,
        "hidden":      True,
        "condition":   lambda s: s["current_level"] >= 5,
    },
    "nivel_10": {
        "name":        "Supremo",
        "description": "Alcanza el nivel 10",
        "icon":        "👑",
        "coins":       1000,
        "xp":          0,
        "hidden":      True,
        "condition":   lambda s: s["current_level"] >= 10,
    },
}
